== gulp-asciidoctor

=== Usage

.Simple
[source,javascript]
----
gulp.pipe(asciidoctor({
  header_footer: false,
  attributes: ['showtitle']
}));
----

.Other argments
[source,javascript]
----
gulp.pipe(asciidoctor({
  header_footer: false,
  safe: 'secure', // unsafe, safe, server or secure
  doctype: 'article', // book, inline
  header_footer: true, // true or false
  attributes: ['showtitle'],
  extension: '.htm'
}));
----


=== install

----
npm install gulp-asciidoctor --save
----

=== Options

=== Plugin specific Options
The following options can be used to configure the Gulp-Plugin

extension:: Sets the output extension of the plugin. Defaults to '.html'
converter:: Sets the converter to use by the underlying AsciiDoctor. If not set, the default converter for the backeend is used

=== AsciiDoctor Options
The following options of the underlying AsciiDoctor can be set

attributes:: Sets additional document attributes, which override equivalently-named attributes defined in the document 
backed:: Sets the converter ot use. Defaults to 'html5'
base_dir:: The base directory for resolving relative resources
doctype:: The doctype. May be 'article', 'book' or 'inline'. Defaults to 'article'
header_footer:: If true, include header and footer in the output. Defaults to 'true'
safe:: The safemode to use. May be 'unsafe', 'safe', 'server' or 'secure'. Defaults to 'unsafe'

=== Important
Do not forget to set the AsciiDoctor option `base_dir` if you want to include
files from locations that are non-relative to the currently proecssed file.

=== Change Log
- V2.1.1: upgrade to asciidoctor 2.1.1, mocha 7.1.0 and replaced gulp-util with replace-ext and plugin-error
- v1.5.5-4: upgrade asciidoctor.js to version 1.5.5-4 and use version consistent with asciidoctor.js.
- v1.0.8: upgrade asciidoctor.js to version 1.5.5-1 and other deps to latest.
- v1.0.7: clean dependences(remove gulp and gulp-debug). 
- v1.0.6: bug fixed
- v1.0.5: fix asciidoctor.js default init bug (Jan/11/2015)
- v1.0.4: bug fixed (Jan/11/2015)
- v1.0.3: bug fixed (Jan/8/2015)
    * Initialize asciidoctor.js only once (Thanks https://github.com/amr[Amr Mostafa])
- v1.0.2: update to asciidoctor 1.5.2

=== TODO
- more asciidoctor functions
- more test case

