= Asciidoctor plugin for Gulp

A https://gulpjs.com[gulp] plugin to support Asciidoctor processing in gulp tasks.

== Installation

----
npm install gulp-asciidoctor --save
----

== Usage
This plugin can be used to integrate Asciidoctor processing in yout gulp tasks. Here are some typical scenarios.

.Simple
[source,javascript]
----
gulp.pipe(asciidoctor({
  standalone: true,
  attributes: ['showtitle']
}));
----

.Other argments
[source,javascript]
----
gulp.pipe(asciidoctor({
  safe: 'secure', // unsafe, safe, server or secure
  doctype: 'article', // book, inline
  standalone: true, // true or false
  attributes: ['showtitle'],
  extension: '.htm'
}));
----

.With templates
[source,javascript]
----
var path = require('path')

gulp.pipe(asciidoctor({
  template_dirs: path.join(__dirname, 'templates')
}));
----

== Options

== Plugin specific Options
The following options can be used to configure the Gulp-Plugin

extension:: Sets the output extension of the plugin. Defaults to '.html'

== AsciiDoctor Options
All options of the underlying AsciiDoctor can be set.

However, the options

* mkdirs
* to_dir
* to_file

will be removed, since they do not make sense in a gulp processing chain.

If not set, the following options will be set to the default values described here

backed:: Sets the converter backend to use. Defaults to 'html5'
base_dir:: The base directory for resolving relative resources. Defaults to the directory of the currently processed file
doctype:: The doctype. May be 'article', 'book' or 'inline'. Defaults to 'article'
safe:: The safemode to use. May be 'unsafe', 'safe', 'server' or 'secure'. Defaults to 'unsafe'
standalone:: Should headers and footers be included. Defaults to 'true'

== Important

=== Base Directory
Do not forget to set the AsciiDoctor option `base_dir` if you want to include
files from locations that are non-relative to the currently proecssed file.

=== Obsolete option 'header_footer'
The 'old' option 'header_footer' will be skipped in favor of the new option 'standalone'.

* If 'header_footer' is set and 'standalone' is not set, the processor will receive 'standalone' = value of 'header_footer' option and the option 'header_footer' will be stripped.
* If both 'header_footer' and 'standalone' are set, the option 'header_footer' will be stripped.

== Change Log
- V2.2.0: upgrade to asciidoctor 2.2.0
- V2.1.1: upgrade to asciidoctor 2.1.1, mocha 7.1.0 and replaced gulp-util with replace-ext and plugin-error
- v1.5.5-4: upgrade asciidoctor.js to version 1.5.5-4 and use version consistent with asciidoctor.js.
- v1.0.8: upgrade asciidoctor.js to version 1.5.5-1 and other deps to latest.
- v1.0.7: clean dependences(remove gulp and gulp-debug). 
- v1.0.6: bug fixed
- v1.0.5: fix asciidoctor.js default init bug (Jan/11/2015)
- v1.0.4: bug fixed (Jan/11/2015)
- v1.0.3: bug fixed (Jan/8/2015)
    * Initialize asciidoctor.js only once (Thanks https://github.com/amr[Amr Mostafa])
- v1.0.2: update to asciidoctor 1.5.2

== TODO
- more test case

